### ISSUE TITLE
Historikoetako PDF botoia sakatzean errorea

### ISSUE THREAD

**Issue by iaramendi** [PasaiakoUdala/ZergaOrdenantzak#24]
Historikoetako PDF botoia sakatzean errore hau ematen du:
The requested URL /doc/064//Datos/Aplikazioak/wwwroot/ayuntamientos/zergaordenantzak.dev/web/doc/064/ZergaOrdenantzak-2016-09-08_135221.pdf was not found on this server.

**Comment by ikerib** [comment]
horiek zerga ordenantzak zaharrak dira, fitxategi horiek igo beharko dira pdf bidez
