### ISSUE TITLE
sesioa ixten da denbora batean

### ISSUE THREAD

**Issue by iaramendi** [PasaiakoUdala/ZergaOrdenantzak#26]
Erabili gabe egonez gero, saioa galtzen du, eta gero agertzen da identifikatzeko interfazea, baina ez IZFEkoa, barnekoa, hau da, IZFEko erabiltzailea eta zerga ordenantzetako pasahitza eskatzen duena. Logikoena ez ixtea sesioa da, IZFEko beste aplikazioak ez dira ixten, nahiz eta utzi orduak irekia eta erabili gabe izan.

**Comment by ikerib** [comment]
Hau sisteman ezartzen den zerbait da. Ticket bat ireki beharko da.

cookie_lifetime¶

type: integer default: null

This determines the lifetime of the session - in seconds. The default value - null - means that the session.cookie_lifetime value from php.ini will be used. Setting this value to 0 means the cookie is valid for the length of the browser session.

Guk ez dugu zehazten beraz php.ini-tik hartzen du. Hori luzatzeko eskatu beharko da, edo dituzten beste aplikazioen berdin ezartzeko.
