### ISSUE TITLE
Errenteriatik

### ISSUE THREAD

**Issue by iaramendi** [PasaiakoUdala/ZergaOrdenantzak#27]
azpiatal bat sortzen baduzu izenbururik eta koderik gabe, eta bertan parrafo berri bat txertatu, pantaila ilunduta geratzen da denbora luzez.

Klik egitean parrafoa sortu duela ikusten da, baina empty hitza agertzen da bere lekuan. Irudian hobeto ikusiko duzu:

**Comment by iaramendi** [comment]
![dibujo](https://cloud.githubusercontent.com/assets/22541918/20263499/55adeb26-aa67-11e6-8018-23d8ebb5b284.JPG)
![dibujo](https://cloud.githubusercontent.com/assets/22541918/20263506/5cfa5752-aa67-11e6-9953-2f55f41e92cd.JPG)

**Comment by ikerib** [comment]
Parrafoarena konpondua egon beharko luke sistema berriarekin.

Empty-arena... hasiera batean horrela dago apropos. Erabiltzen dudan liburutegiak textu bat espero du, ez badu aurkitzen Empty idazten du eta aldatzeko aukera ematen du.

Empty hori gero ez da inprimitzen, nik ez dut ikusten arazorik hori pintatzearekin... gerora tituloa jarri nahi badute, nola egingo dute bestela?

Empty jarri beharrean, jar daiteke beste zerbait. "Empty" hori lehenetsitako textua da liburutegian.
