### ISSUE TITLE
Errenteriatik II - azpiataletan parrafoak

### ISSUE THREAD

**Issue by iaramendi** [PasaiakoUdala/ZergaOrdenantzak#28]
Azpiatal batean parrafo bat gehitzerakoan ez da argi ikusten zein posizioetan agertzen den. Sortutako parrafo hori ondoren igo eta jeitsi nahi bada, errorea ematen du.

**Comment by iaramendi** [comment]
![dibujo2](https://cloud.githubusercontent.com/assets/22541918/20264271/f4b8fc76-aa6a-11e6-9684-a81aa2bdfd7b.JPG)

**Comment by iaramendi** [comment]
presa pixkat dute akats honekin, ahal badezu zuzendu hau lehendabizi

**Comment by ikerib** [comment]
Parrafoak gehitzeko sistema aldatu dut. Pentsatu nahi dut aldaketa hauekin hau konponduko dela
