### ISSUE TITLE
errorea ordenantza baten parrafoa ezabatzerakoan X botoiarekin

### ISSUE THREAD

**Issue by iaramendi** [PasaiakoUdala/ZergaOrdenantzak#43]
[2/2] MethodNotAllowedHttpException: No route found for "GET /admin/ordenantzaparrafoa/793": Method Not Allowed (Allow: DELETE)  + 

ERROR - Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /admin/ordenantzaparrafoa/793": Method Not Allowed (Allow: DELETE)" at /Datos/Aplikazioak/wwwroot/ayuntamientos/zergaordenantzak.dev/var/cache/dev/classes.php line 1972

**Comment by ikerib** [comment]
Kodean ez dago akatsik. Antivirus-a desgaitzen denean frogatu beharko dugu, guztia bat etor bait daiteke.

Antivirus-ak JS fitxategien karga mozten du, eta beraz web orriak funtzionalitatea galtzen du. Zerbait aleatorioa da, ez du beti fitxategi berbera eteten
